### ISSUE TITLE
Update for 1.x.x?

### ISSUE THREAD

**Issue by Neproify** [julianlam/nodebb-plugin-github-embed#14]
Hello @julianlam can you update this plugin for 1.x.x? I really like features like this. Thank you!

**Comment by julianlam** [comment]
46447e017224c761acf8a4fa18a4324e6245747b

Thanks for the reminder! :smile: There are no breaking changes for this plugin so I have cleared it for inclusion into nbbpm again. Try refreshing the plugin list in a couple minutes.
