### ISSUE TITLE
Multi-Project Support

### ISSUE THREAD

**Issue by Nicklas2751** [julianlam/nodebb-plugin-github-embed#15]
Hello,

I think it would be really cool to see an multi-project support.
You could add an option to activate it and the use `Projectname/#IssueNumber` to recognize which project is meant.

**Comment by julianlam** [comment]
Hi @Nicklas2751 -- we actually _do_ support that, the syntax is `repoowner/project#issuenum`, just like GitHub.

e.g. NodeBB/nodebb-plugin-pushbullet#1
