### ISSUE TITLE
referencing a commit blocks forum

### ISSUE THREAD

**Issue by Jey-Cee** [julianlam/nodebb-plugin-github-embed#20]
Today we have a problem with the plugin. A user referenced a github commit, the topic and also the category could not be loaded for around 30 minutes. There was no error or something in the browser console and the forum log.
It looks like the plugin had problems with resolving the commit. After the commit was cached it works normal and shows the commit.

I checked this with other commits, result was the same.

nodebb version 1.12.2
plugin version 0.7.4

**Comment by julianlam** [comment]
That's very odd, does this continue to happen even today? I am wondering if it was a transient problem with reaching GitHub's servers...

**Comment by Jey-Cee** [comment]
Can not say, we have disabled the plugin because had a lot of problems and saw 186k 503 errors within 24 hours. I will try it during the night when there are not that much users are online.

**Comment by julianlam** [comment]
@Jey-Cee might as well leave it out. I'll take a look today and see what I can find. Thanks for reporting!

**Comment by julianlam** [comment]
Oh, while I have you, can you share the commit that your users were trying to embed? It might happen on all commits, but just in case it is not, it would be good to know yours.

**Comment by julianlam** [comment]
Currently not seeing any issues here:

![image](https://user-images.githubusercontent.com/923011/69268221-b6544080-0b9c-11ea-8244-c06da2be3a1d.png)

Do you have an API key and secret defined? I do not... is GitHub blocked where your server is hosted (e.g. China?)

**Comment by Jey-Cee** [comment]
Here is my test link: https://github.com/ioBroker/ioBroker.javascript/commit/cce09b21a269ba17f38a32acea99cc089f935123

No Api Key and Secret.

 Hm is hosted in germany.

**Comment by julianlam** [comment]
Unfortunately still unable to reproduce, I'll need a set of clean reproduction steps if possible.

![image](https://user-images.githubusercontent.com/923011/69677072-17ce5080-1070-11ea-95d0-2c1e64327e04.png)
